version: '3.1'

services:

  app:
    build:
      context: .
    volumes:
      - bundle:/bundle
      - .:/news
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    build: ./docker/mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

volumes:
  bundle: